version: "3.9"

services:
  test:
    build: .
    depends_on:
      - backend
    environment:
      BACKEND_BASE_URL: http://backend:8080
    entrypoint: ["wait-for-it", "backend:8080", "--timeout=400", "--strict", "--", "bats", "travel-sample-backend.bats"]

  backend:
    build: "https://github.com/couchbaselabs/try-cb-python.git#7.0"
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - CB_HOST
      - CB_USER
      - CB_PSWD
    command: $CB_HOST $CB_USER $CB_PSWD
    container_name: test-try-cb-api
  
  db:
    image: couchbase/server-sandbox:7.0.0
    ports:
      - "8091-8095:8091-8095"
      - "11210:11210"
    expose: # expose ports 8091 & 8094 to other containers (mainly for backend)
      - "8091"
      - "8094"
    container_name: test-couchbase-sandbox-7.0.0
